# Generated by Django 3.2.19 on 2023-07-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Принят', 'Принят'), ('В сборке', 'В сборке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Закрыт', 'Закрыт')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Нормально'), (2, 'Плохо'), (1, 'Ужасно')]),
        ),
    ]
