# Generated by Django 3.2.19 on 2023-08-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Принят', 'Принят'), ('В сборке', 'В сборке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Закрыт', 'Закрыт')], default='Создан', max_length=255, null=True),
        ),
    ]
