# Generated by Django 4.1.7 on 2023-07-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_orderproduct_item_orderproduct_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
