# Generated by Django 4.1.7 on 2023-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cоздан', 'Создан'), ('Принят', 'Принят'), ('В сборке', 'В сборке'), ('В пути', 'В пути'), ('Доставлен', 'Доставлен'), ('Закрыт', 'Закрыт')], default='Создан', max_length=255, null=True),
        ),
    ]
