# Generated by Django 4.1.7 on 2023-07-08 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
