# Generated by Django 4.1.7 on 2023-07-10 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0014_product_favorite_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite_product',
        ),
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
