# Generated by Django 4.1.7 on 2023-07-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='chosen',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
